/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_drecom_spice_hockeyapp_HockeyApp */

#ifndef _Included_jp_co_drecom_spice_hockeyapp_HockeyApp
#define _Included_jp_co_drecom_spice_hockeyapp_HockeyApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_drecom_spice_hockeyapp_HockeyApp
 * Method:    setUpBreakpad
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jp_co_drecom_spice_hockeyapp_HockeyApp_setUpBreakpad
  (JNIEnv *env, jclass cls, jstring file_path);

#ifdef __cplusplus
}
#endif
#endif
